export {default as Jumbotron} from './jumbotron'
export {default as Footer} from './footer'
export {default as Faq} from './faq'
export {default as Banner} from './banner'
export {default as EmailSection} from './emailsection'
export {default as Login} from './login'
export {default as Signup} from './signup'
export {default as Home} from './home'